# Generated by Django 4.2.7 on 2023-11-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('назва_кінотеатру', models.CharField(max_length=255)),
                ('ціни_на_квитки', models.FloatField()),
                ('кількість_місць', models.IntegerField()),
                ('адреса', models.CharField(max_length=255)),
                ('телефон', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('назва_фільму', models.CharField(max_length=255)),
                ('жанр', models.CharField(max_length=50)),
                ('тривалість', models.IntegerField()),
                ('рейтинг', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_початку_показів', models.DateField()),
                ('термін_показу', models.IntegerField()),
                ('код_кінотеатру', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cinema')),
                ('код_фільму', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.film')),
            ],
        ),
    ]
